name: Scrape latest data

on:
  push:
  workflow_dispatch:
  schedule:
    - cron: "6 * * * *"

jobs:
  scheduled:
    runs-on: ubuntu-latest
    steps:
      - name: Check out this repo
        uses: actions/checkout@v2
      - name: Setup Deno
        uses: denoland/setup-deno@v1
        with:
          deno-version: v1.x
      - name: Fetch latest data
        run: deno run --allow-net --allow-write --unsafely-ignore-certificate-errors=www.loipenportal.de .github/workflows/scrape.js
      - name: Commit and push if it changed
        run: |-
          git config user.name "Automated"
          git config user.email "actions@users.noreply.github.com"
          git add -A
          timestamp=$(date -u)
          git commit -m "Latest data: ${timestamp}" || exit 0
          git push
