name: Scrape latest data

on:
  push:
  workflow_dispatch:
  schedule:
    - cron: "6 * * * *"

jobs:
  scheduled:
    runs-on: denoland/deno:latest
    steps:
      - name: Check out this repo
        uses: actions/checkout@v2
      - name: Fetch latest data from loipenportal
        run: |-
          deno run --allow-net --allow-write --unsafely-ignore-certificate-errors=www.loipenportal.de loipenportal/scrape.ts
      - name: Commit and push if it changed
        run: |-
          git config user.name "Automated"
          git config user.email "actions@users.noreply.github.com"
          git add -A
          git commit -m "Latest data: ${date -u}" || exit 0
          git push
